language: objective-c
osx_image: xcode7.2

install:
  - ./install.sh

script:
  - xctool -workspace Antidote.xcworkspace -scheme Antidote -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s' test
