language: objective-c
osx_image: xcode6.4

before_install:
    - brew update; brew update
    - brew install uncrustify
    - pod install

script:
    - xctool -workspace Antidote.xcworkspace -scheme Antidote -sdk iphonesimulator build
    - ./run-uncrustify.sh --check
