language: objective-c

before_install:
    - gem install cocoapods
    - brew update
    - brew unlink xctool
    - brew install xctool
    - pod install

script: xctool -workspace Antidote.xcworkspace -scheme Antidote -sdk iphonesimulator build
