language: objective-c

before_install:
    - gem install cocoapods
    - brew update
    - brew unlink xctool
    - brew install xctool
    - brew install uncrustify
    - pod install

script:
    - xctool -workspace Antidote.xcworkspace -scheme Antidote -sdk iphonesimulator build
    - ./run-uncrustify.sh --check
